import math
Vanligkorv2 = int(input("Hur många elever vill ha 2 vanliga korvar? :"))
Vanligkorv3 = int(input("Hur många elever vill ha 3 vanliga korvar? :"))
Vegankorv2 = int(input("Hur många elever vill ha 2 veganska korvar? :"))
Vegankorv3 = int(input("Hur många elever vill ha 3 veganska korvar? :"))
Dryck = int(input("Hur många elever vill ha dryck?: "))

packagePrice = 34.95

Antalvanligkorv = math.ceil(((Vanligkorv2 * 2) + (Vanligkorv3 * 3)) / 8)
Antalvegankorv = math.ceil(((Vegankorv2 * 2 ) + (Vegankorv3 *3)) / 4)
print ("Korvkollen 1.0.1:")
print ("-----------------------------------")
print ("Antal vanliga korvar : ", ((Vanligkorv2 * 2) + (Vanligkorv3 * 3)))
print ("Antal veganska korvar : ", ((Vegankorv2 * 2 ) + (Vegankorv3 *3)))
print ("Antal drickor: ", Dryck)
print ("-----------------------------------")
print ("-      INKÖPSLISTA       -")
print ("-----------------------------------")
print ("Vanlig korv:", (Antalvanligkorv), "Förpackningar")
print ("Vegansk korv:", (Antalvegankorv), "Förpackningar")
print ("Dryck:", (Dryck), "drickor")
print ("-----------------------------------")
totalaKorvpriset = packagePrice * (Antalvegankorv)

print ((20.95 * (Antalvanligkorv)) + totalaKorvpriset + (13.95 * (Dryck)), "SEK"  )
print ("-----------------------------------")
pris = float(20.95 * (Antalvanligkorv)) + (packagePrice *(Antalvegankorv)) + (13.95 * (Dryck))
pris = int(pris)
print (pris)